services:
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: meduser
      POSTGRES_PASSWORD: medpass
      POSTGRES_DB: medhealth
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: